<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-QMA3PVOQ" failures="1" tests="5" name="com.automationexercise.tests.TC_ECOM_Tests" time="95.712" errors="0" timestamp="2025-09-03T21:23:12 IST" skipped="0">
  <testcase classname="com.automationexercise.tests.TC_ECOM_Tests" name="TC_ECOM_TestCase_001" time="36.162">
    <failure message="Page load time exceeded. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Page load time exceeded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.automationexercise.tests.TC_ECOM_Tests.TC_ECOM_TestCase_001(TC_ECOM_Tests.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- TC_ECOM_TestCase_001 -->
  <testcase classname="com.automationexercise.tests.TC_ECOM_Tests" name="TC_ECOM_TestCase_005" time="4.555"/>
  <testcase classname="com.automationexercise.tests.TC_ECOM_Tests" name="TC_ECOM_TestCase_002" time="14.795"/>
  <testcase classname="com.automationexercise.tests.TC_ECOM_Tests" name="TC_ECOM_TestCase_003" time="35.606"/>
  <testcase classname="com.automationexercise.tests.TC_ECOM_Tests" name="TC_ECOM_TestCase_004" time="4.594"/>
</testsuite> <!-- com.automationexercise.tests.TC_ECOM_Tests -->
